#!/usr/bin/env bash
# Script that configure an Ubuntu server


sed -i.bak '/127.0.0.1.*localhost/d; /localhost/d; /facebook.com/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
