#!/usr/bin/env bash
# Script that configure an Ubuntu server

# Remove any existing entries for localhost and facebook.com
sed -i '/localhost/d' /etc/hosts # sed -> Stream editor 
sed -i '/facebook.com/d' /etc/hosts # /d -> Delete

# Add the new entries
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
