#!/usr/bin/env bash
# Script that configures an Ubuntu server so that localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

# Filter out old entries and save to temp file
grep -v localhost /etc/hosts | grep -v facebook.com > /tmp/newhosts

# Add new entries
echo "127.0.0.2 localhost" >> /tmp/newhosts
echo "8.8.8.8 facebook.com" >> /tmp/newhosts

# Overwrite the hosts file
cat /tmp/newhosts > /etc/hosts

# Clean up
rm /tmp/newhosts